//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almaz
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlmazEnt : DbContext
    {
        public AlmazEnt()
            : base("name=AlmazEnt")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказчики> Заказчики { get; set; }
        public virtual DbSet<Изготовление> Изготовление { get; set; }
        public virtual DbSet<Изделия> Изделия { get; set; }
        public virtual DbSet<Металл> Металл { get; set; }
        public virtual DbSet<Ювелир> Ювелир { get; set; }
    }
}
