//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almaz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Изготовление
    {
        public int ID_изготовления { get; set; }
        public Nullable<int> Изделие { get; set; }
        public Nullable<int> Заказчик { get; set; }
        public Nullable<int> Ювелир { get; set; }
        public string Цена { get; set; }
    
        public virtual Заказчики Заказчики { get; set; }
        public virtual Изделия Изделия { get; set; }
        public virtual Ювелир Ювелир1 { get; set; }
    }
}
